/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {

}

fun main() {
    println("Candela de la Cruz")
    println("22 de abril de 2025")
    mostrarTiposDeDatos()
    rectangulo()
    println(NegPos0(5))
    println(esParOImpar(5))

}

fun mostrarTiposDeDatos() {
    val nombre: String = "Candela"
    val edad: Int = 16
    val altura: Double = 1.63
    val esEstudiante: Boolean = true
    
    println("Nombre: $nombre")
    println("Edad: $edad")
    println("Altura: $altura")
    println("Es estudiante: $esEstudiante")
}

fun rectangulo() {
    val height: Int = 35
    val width: Int = 3
    val area = height * width

    println("La altura del rectángulo es: $height y el ancho es: $width. por lo tanto su área es de: $area" )
}
fun esParOImpar(numero: Int): String {
    return when {
        numero % 2 == 0 -> "Par"
        else -> "Impar"
    }
}

fun NegPos0(numero:Int): String {
    return when {
        numero > 0 -> "El número es positivo"
        numero < 0 -> "El número es negativo"
        else -> "El número es cero"
    }
}
    


