/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {

}

fun main() {
    println("Candela de la Cruz")
    println("22 de abril de 2025")
    rectangulo()

}

fun rectangulo() {
    val height: Int = 35
    val width: Int = 3
    val area = height * width

    println("La altura del rectángulo es: $height y el ancho es: $width. por lo tanto su área es de: $area" )
}
